% =========================================================================
% Practical 2: Mandelbrot-Set Serial vs Parallel Analysis
% =========================================================================
%
% GROUP NUMBER: 8
%
% MEMBERS:
%   - Shaun Beautement, BTMSHA001
%   - Neo Vorsatz, VRSNEO001

clear;

global output_dir;
global output_file;
output_dir = "output_images";
output_file = "analysis_results.csv";

%% ========================================================================
%  PART 1: Mandelbrot Set Image Plotting and Saving
%  ========================================================================
%
% TODO: Implement Mandelbrot set plotting and saving function
function mandelbrot_plot(plot) %Add necessary input arguments
    [rows, cols] = size(plot);
    imwrite(normalized_manual, strcat(output_dir,"/mandelbrot_", ...
        int2str(rows),"x",int2str(cols)));
end

%% ========================================================================
%  PART 2: Serial Mandelbrot Set Computation
%  ========================================================================`
%
%TODO: Implement serial Mandelbrot set computation function
function mandelbrot_serial(varargin) %Add necessary input arguments 
    
end
% Neo's recommended function header:
% function plot = mandelbrot_parallel(width, height, max_iterations)
% "plot" is a matrix of the coordinates, where 1 means "in the set", and 0
% means otherwise.
% the "width" and "height" count pixels
% "max_iterations" is self-explanatory

%% ========================================================================
%  PART 3: Parallel Mandelbrot Set Computation
%  ========================================================================
%
%TODO: Implement parallel Mandelbrot set computation function
function mandelbrot_parallel(varargin) %Add necessary input arguments 
    
end
% Neo's recommended function header:
% function plot = mandelbrot_parallel(width, height, max_iterations)
% "plot" is a matrix of the coordinates, where 1 means "in the set", and 0
% means otherwise.
% the "width" and "height" count pixels
% "max_iterations" is self-explanatory

%% ========================================================================
%  PART 4: Testing and Analysis
%  ========================================================================
% Compare the performance of serial Mandelbrot set computation
% with parallel Mandelbrot set computation.

function run_analysis_()
    %Array conatining all the image sizes to be tested
    image_sizes = [
        [800,600],   %SVGA
        [1280,720],  %HD
        [1920,1080], %Full HD
        [2048,1080], %2K Cinema
        [2560,1440], %2K QHD
        [3840,2160], %4K UHD
        [5120,2880], %5K
        [7680,4320]  %8K UHD
    ]

    max_iterations = 1000; 
    
    %TODO: For each image size, perform the following:
    %   a. Measure execution time of mandelbrot_serial
    %   b. Measure execution time of mandelbrot_parallel
    %   c. Store results (image size, time_serial, time_parallel, speedup)  
    %   d. Plot and save the Mandelbrot set images generated by both methods
    
end